spring.application.name=discografia

# Cadena de conexión estandarizada para el driver de MongoDB Atlas.
spring.mongodb.uri=mongodb+srv://eva2_spring:Ka5zh8TyuzWq5gCw@cluster-spring.kribdki.mongodb.net/?appName=cluster-spring

# Se indica el nombre de la base de datos que se utilizará en la aplicación.
spring.mongodb.database=discografica-db